name: Release

on:
  push:
    tags:
      - 'v*'  # Déclenche sur tous les tags commençant par 'v' (ex: v1.0.0)
      # Ou plus spécifique :
      # - 'v[0-9]+.[0-9]+.[0-9]+' # Seulement pour les tags semver

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false